# Generated by Django 3.1.3 on 2023-10-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20231007_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='stz',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
