# Generated by Django 3.1.3 on 2023-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_transactions_stz'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='room',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
