# Generated by Django 5.0 on 2024-02-26 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_rooms_id_alter_users_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rooms',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
