# Generated by Django 5.0 on 2024-02-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0003_delete_rooms_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=600)),
            ],
        ),
    ]
