# Generated by Django 5.0 on 2024-03-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0002_remove_book_stream_delete_availability_delete_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=255, verbose_name='Stream Name')),
            ],
        ),
    ]
