# Generated by Django 3.1.3 on 2023-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_transactions_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='srbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('dat_e', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
    ]
