# Generated by Django 3.1.3 on 2023-10-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('stz', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dbooking',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='mbooking',
            name='mode',
        ),
    ]
