# Generated by Django 5.0 on 2024-03-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_dbooking_id_alter_mbooking_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requests',
            new_name='Request',
        ),
    ]
